<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Thematique;

class ThematiquesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Thematique::truncate();

        Thematique::create(['name'=>'Intersectionnalité', 'desc' => 'L’intersectionnalité est une approche ayant été popularisée à la fin des années 1980 par la juriste et professeure de droits américaine Kimberlé Crenshaw. Il s’agit d’un outil d’analyse et une approche en intervention visant à comprendre les êtres humains comme la résultante des croisements de leurs différentes positions sociales (ex. genre et classe et capacité). Les croisements identitaires font état des différents systèmes d’oppression interagissant et se renforçant mutuellement chez une personne. Une femme noire en chaise roulante, par exemple, se retrouve aux intersections du sexisme, du racisme et du capacitisme. Son positionnement identitaire la rend susceptible de vivre des oppressions des trois systèmes à la fois. L’intersectionnalité reconnaît ainsi l’aspect unique et complexe de l’expérience individuelle de chacun·e, entre ses points de discrimination et ses privilèges (Crenshaw, K., 2016). Dans un contexte d’intimidation, l’expérience de la situation varie grandement d’un.e individu·e à l’autre en fonction des positionnements identitaires des personnes concernées et du rôle joué dans l’incidence. Il importe d’aborder chaque situation d’intimidation avec une lunette intersectionnelle afin de prendre en compte la globalité de la situation pour chaque individu·e.']);

        Thematique::create(['name'=>'Le cyberespace', 'desc' => 'Le cyberespace représente le plus vaste canal de communication accessible mondialement depuis l’accès à un appareil électronique ayant accès à internet. Il regroupe notamment les sites internet, les forums et les médias sociaux, ayant comme principales fonctions la production, la diffusion de contenu et l’interaction entre les internautes. L’intimidation dans le cyberespace, la cyberintimidation, regroupe les rumeurs, les insultes, les menaces, les propos hostiles et le partage de photos et d’informations privées d’une personne, sans son consentement, par
        messages textes, courriels et sur les réseaux sociaux (Gouvernement du Québec, 2023). L’un des plus importants facteurs de risque quant à la cyberintimidation est le fait d’avoir une utilisation fréquente d’internet et des médias sociaux. En effet, plus une personne fréquente le cyberespace, plus elle risque d’être une cible, témoin ou auteur·e d’intimidation (INSPQ, 2020). Les plateformes de jeux vidéo en ligne multijoueur·euses sont également des espaces à haut risque d’incidents d’intimidation et de harcèlement. L’anonymat que peut prodiguer le cyberespace fait de ce dernier un espace propice au désengagement et à la déresponsabilisation
        des internautes face aux conséquences de publier des messages haineux, inappropriés et harcelants envers autrui. D’ailleurs, certaines personnes n’adoptant pas de comportements intimidateurs dans la vie physique, le font en ligne en raison du sentiment d’impunité que l’anonymat leur procure.

        Les jeunes sont les internautes les plus touché·es par la cyberintimidation en raison de leur usage important des plateformes en ligne. Les adultes et les organisations peuvent également être la cible ou auteur·es d’harcèlement et de cyberintimidation (INSPQ, 2020). 
        
        Le caractère potentiellement viral des publications sur le web augmente la sévérité des conséquences pouvant être vécues par les personnes ciblées. En effet, la cyberintimidation, qu’il
        s’agisse d’insultes lancées à une personne, d’une atteinte à sa vie privée ou à sa réputation, a le potentiel d’atteindre un auditoire pratiquement illimité (Gouvernement du Québec, 2023).
        
        Un bon sentiment de sécurité en milieu scolaire, des environnements familiaux et sociaux positifs, une supervision parentale adéquate lors de l’utilisation des technologies de l’information par les jeunes, une bonne gestion des émotions et une bonne estime de soi chez les internautes sont certains des facteurs de protection pouvant moduler les risques de la cyberintimidation chez les cibles et les auteur·es (INSPQ, 2023b).']);

        Thematique::create(['name'=>'Microagression', 'desc' => 'Une microagression est un acte subtil de discrimination interpersonnelle posé au quotidien envers les personnes issues de groupes marginalisés (ex. personnes racisées, personnes grosses, personne trans, etc.). Les microagressions peuvent être verbales (questions insensibles, blagues déplacées, compliments non désirés) et non-verbales (attitudes dénigrantes ou indifférentes, regard désapprobateur) et sont généralement perpétrées de façon automatique et inconsciente (Espaillat, A. et coll., 2019). Contrairement aux actes discriminatoires, les microagressions sont plus difficiles à remarquer, elles prennent forme dans les subtilités, les non-dits, et peuvent être dissimulées par les biais et préjugés sociétaux. Malgré leur caractère subtil, elles peuvent avoir un impact considérable sur la santé et le bien-être des personnes qui en sont la cible. Une personne vivant un cumul de microagressions peut développer des symptômes et des réactions physiques semblables à ce qu’un traumatisme peut provoquer, tels des symptômes anxieux, dépressifs et une hypervigilance marquée (Smith Haghighi, 2023).']);

        Thematique::create(['name'=>'Grossophobie', 'desc' => 'La grossophobie désigne l’ensemble des discriminations subies par les personnes ayant un corps perçu gros. Ces dernières peuvent être multiples et être exercées à divers niveaux ; professionnel, médical, institutionnel, social, relationnel, etc. Une société grossophobe en est une qui appose une valeur morale et un niveau de désirabilité sociale selon la grosseur des corps. Un
        corps perçu mince y représente l’idéal à atteindre et est associé à des qualificatifs positifs (discipline, santé, performance, beauté), tandis qu’un corps perçu gros est associé à des qualificatifs négatifs (paresse, indésirable, dégoût, coûteux pour l’état) (Association pour la santé publique du Québec, 2023a; Association pour la santé publique du Québec, 2023b). La représentation médiatique péjorative et peu représentative de la diversité des vécus et des expériences des personnes vivant dans un corps gros contribue insidieusement à la perpétuité des préjugés et à l’intériorisation des messages dépréciateurs chez les personnes grosses (Tokozani Sakala, S., 2022).']);

        Thematique::create(['name'=>'Capacitisme', 'desc' => 'Le capacitisme est une discrimination basée sur les stéréotypes et préjugés stigmatisant les personnes dont les capacités physiques, sociales, émotionnelles, sensorielles ou intellectuelles diffèrent des représentations sociales dominantes d’une personne considérée « capable ». Une personne est considérée « capable » lorsqu’elle est en mesure de contribuer à la société d’une
        manière uniforme et standardisée (Parent, L., 2022). Le capacitisme exprime l’idéologie que les personnes ayant des capacités différentes de la norme sociale sont inférieures, incapables de prendre des décisions pour elles-mêmes et moins aptes à participer et contribuer à la société (L’Encyclopédie canadienne, 2023). Le capacitisme peut se manifester par des attitudes, des comportements, des paroles portant préjudice à une personne ou un groupe de personnes ayant des incapacités (personnes en situation de handicap, personnes neurodivergentes, etc.). La discrimination basée sur les capacités peut s’exercer dans toutes les sphères de vie occupées
        par un·e individu·e, notamment socialement par la stigmatisation subie et le manque d’accessibilité, l’aménagement des espaces publics, professionnellement par les barrières d’accès à des emplois adaptés et médicalement par une prise en charge mettant les incapacités à l’avant-plan, devant l’individu·e (L’Encyclopédie canadienne, 2023).']);

        Thematique::create(['name'=>'Sexisme', 'desc' => 'Le sexisme est une forme de discrimination basée sur la croyance qu’un sexe, ou un genre, est supérieur aux autres. Cette croyance provoque des préjugés envers les genres considérés moindres, en l’occurrence, toutes les personnes ne s’identifiant pas homme. Les femmes, les personnes non-binaires, les personnes trans peuvent tou·tes être la cible de sexisme. Le sexisme peut s’exprimer par des attitudes, des comportements et des paroles visant à dénigrer, amoindrir et prendre le pouvoir sur les genres considérés moins dominants. Les préjugés sexistes, étant enracinés socialement, provoquent du sexisme institutionnel pouvant se faire remarquer à grande échelle notamment par l’inégalité persistante des salaires entre les genres pour un poste à compétences égales et par la sous-représentation des personnes de genre non-masculin se retrouvant dans des postes de direction et de pouvoir à travers le monde (PNUD, 2020).']);

        Thematique::create(['name'=>'Racisme', 'desc' => 'Le racisme est l’idéologie selon laquelle il existe plusieurs races chez les êtres humains, lesquelles sont inégales dans leur valeur les unes face aux autres. En Occident, les personnes blanches représentent la majorité. De ce fait, toutes les personnes non-blanches font partie de ce qu’on appelle des populations minorisées ou racisées. Les pouvoirs sont répartis de manière
        inéquitable dans la société, les personnes des groupes dominants ont typiquement davantage de privilèges que les personnes des groupes minoritaires. Ce raisonnement peut provoquer des biais ou des préjugés et justifier l’adoption, parfois inconsciente, parfois consciente, de traitements, de comportements ou d’attitudes discriminatoires par les individu·es et les institutions envers les personnes issues de minorités ethnoculturelles. L’intimidation basée sur le racisme peut découler en des attitudes et comportements hostiles et oppressifs répétés envers une personne, dans le but de la diminuer, l’offenser et l’exclure socialement, en raison de son appartenance ethnoculturelle ou de la couleur de sa peau, (Commission des droits de la personne et des droits de la jeunesse, 2021; Université de Montréal, s.d.).']);

        Thematique::create(['name'=>'Homophobie', 'desc' => 'L’homophobie est une forme de discrimination directe ou indirecte fondée sur l’orientation sexuelle réelle ou perçue d’une personne. Elle peut s’exprimer par des attitudes et comportements hostiles, méprisants, dégradants et haineux provoquant la marginalisation et la stigmatisation sociale des personnes homosexuelles. L’homophobie peut également affecter toute personne dont l’apparence ou le comportement est considéré non-confome aux stéréotypes traditionnels de la féminité et de la masculinité (Interligne, 2023).']);

        Thematique::create(['name'=>'Transphobie', 'desc' => 'La transphobie est une forme de discrimination ayant pour cible les personnes trans, non-binaires, fluides dans le genre et toute personne dont le genre est considéré comme non-conforme (Interligne, 2023). Les personnes trans, non-binaires, fluides ou non conformes dans le genre sont des personnes dont le sexe assigné à la naissance ne correspond pas au genre ressenti. Les personnes cisgenres, personnes dont le sexe assigné à la naissance correspond au genre ressenti, sont désignées comme la norme, ce qui est naturel (Dubuc, D., 2017). Or, lorsque le concept du genre est étudié sous l’optique qu’il est une construction sociale, il est mis en lumière que ce qui est considéré comme un comportement genré approprié varie d’une époque à l’autre et d’une société à l’autre (Goyer, M.-F., 2020). Ce qui est construit et perpétré par la société et la culture n’est pas naturel (Goyer, M.-F., 2020). La transphobie peut se manifester par des actes de violence isolés ou répétés sous diverses formes, telles que verbale, physique, psychologique et institutionnelle (Gouvernement du Québec, 2023). Les violences transphobes institutionnelles peuvent inclure des difficultés à se trouver un logement, un emploi, vivre des barrières à l’accès de services essentiels, dont des soins de santé de qualité et adaptés aux besoins des personnes (Gouvernement du Québec, 2023).']);

        Thematique::create(['name'=>'Classisme', 'desc' => 'Le classisme est une forme de discrimination basée sur l’appartenance d’une personne à une classe sociale réelle ou présumée. Le classisme exprime l’idéologie que le positionnement socioéconomique d’une personne dans une société donnée fait état de la classe sociale à laquelle elle appartient. Ce système d’oppression prétend qu’une classe sociale est supérieure aux autres, justifiant ainsi la place dominante qu’elle occupe dans la société. Une société classiste valorise les personnes riches, éduquées, cultivées et fait généralement passer leurs intérêts avant ceux des personnes des classes considérées inférieures (Stanford University, s.d.). Dans la vie courante, les incidences discriminatoires peuvent se manifester de manière consciente ou inconsciente, tant les préjugés classistes peuvent être ancrés dans la culture populaire et l’inconscient collectif. Il peut s’agir de comportements, d’attitudes, de paroles hostiles, méprisantes, infantilisantes envers certaines classes sociales impliquant typiquement unjugement de valeur et un sentiment de supériorité. Les personnes aux intersections de divers systèmes d’oppression (ex. racisme, capacitisme, grossophobie) sont à risque d’être victimes de classisme en raison des conséquences des autres systèmes sur leur qualité de vie, leur santé mentale, physique, leurs difficultés à trouver un emploi, leur santé financière, etc. (Stanford University, s.d.).

        Exemples de comportements, attitudes classistes :
            - Regard social défavorable quant au mode de vie d’une personne en situation d’itinérance;
            - Jugements, moqueries et invalidation d’une personne et de ses propos en raison des fautes d’orthographes dans son message sur les réseaux sociaux;
            - Sous-estimation et exclusion sociale d’une personne s’exprimant dans un langage populaire dans un lieu fréquenté par des personnes de classes intellectuelles jugées supérieures.']);

        Thematique::create(['name'=>'Âgisme', 'desc' => 'L’âgisme est une forme de discrimination basée sur les stéréotypes et préjugés stigmatisant le vieillissement. Comme toute autre forme de discrimination, l’âgisme s’inscrit dans une dynamique de pouvoir. Celle-ci sous-tend une hiérarchisation sociale des personnes selon leur âge et considère la jeunesse comme étant supérieure à la vieillesse. L’âgisme peut se manifester sous
        forme d’attitudes et de comportements dépréciateurs, abusifs et infantilisant auprès des personnes aînées et de façon systémique par les choix de services, installations et règlements n’étant fréquemment pas adaptés aux besoins des citoyen·nes aîné·es (ONU, 2021; Officer, A. et coll., 2020). La mise à distance des âiné·es peut mener à leur exclusion de diverses sphères de vie, notamment professionnelles, sociales et médiatiques, renforcer les préjugés à leur égard et avoir d’importantes conséquences sur leur santé et bien-être global (ONU, 2021).']);

        Thematique::create(['name'=>'Adultisme', 'desc' => 'L’âgisme est une forme de discrimination basée sur les stéréotypes et préjugés stigmatisant le vieillissement. Comme toute autre forme de discrimination, l’âgisme s’inscrit dans une dynamique de pouvoir. Celle-ci sous-tend une hiérarchisation sociale des personnes selon leur âge et considère la jeunesse comme étant supérieure à la vieillesse. L’âgisme peut se manifester sous
        forme d’attitudes et de comportements dépréciateurs, abusifs et infantilisant auprès des personnes aînées et de façon systémique par les choix de services, installations et règlements n’étant fréquemment pas adaptés aux besoins des citoyen·nes aîné·es (ONU, 2021; Officer, A. et coll., 2020). La mise à distance des âiné·es peut mener à leur exclusion de diverses sphères de vie, notamment professionnelles, sociales et médiatiques, renforcer les préjugés à leur égard et avoir d’importantes conséquences sur leur santé et bien-être global (ONU, 2021).']);

        Thematique::create(['name'=>'Enfants', 'desc' => 'L’âgisme est une forme de discrimination basée sur les stéréotypes et préjugés stigmatisant le vieillissement. Comme toute autre forme de discrimination, l’âgisme s’inscrit dans une dynamique de pouvoir. Celle-ci sous-tend une hiérarchisation sociale des personnes selon leur âge et considère la jeunesse comme étant supérieure à la vieillesse. L’âgisme peut se manifester sous
        forme d’attitudes et de comportements dépréciateurs, abusifs et infantilisant auprès des personnes aînées et de façon systémique par les choix de services, installations et règlements n’étant fréquemment pas adaptés aux besoins des citoyen·nes aîné·es (ONU, 2021; Officer, A. et coll., 2020). La mise à distance des âiné·es peut mener à leur exclusion de diverses sphères de vie, notamment professionnelles, sociales et médiatiques, renforcer les préjugés à leur égard et avoir d’importantes conséquences sur leur santé et bien-être global (ONU, 2021).']);

        Thematique::create(['name'=>'Adolescent·es', 'desc' => 'L’un des moyens fréquemment employés par les personnes intimidatrices est de s’en prendre aux caractéristiques singulières des individu·es, à leurs différences. L’apparence physique, le poids, les identités et expressions de genre, les handicaps physiques, les incapacités et limitations cognitives, les appartenances ethnoculturelles et les croyances religieuses ou spirituelles en sont des exemples. Comme il est fréquent que les adolescent·es acquièrent davantage d’autonomie en vieillissant, notamment quant à leur utilisation d’internet et des médias
        sociaux, celleux-ci deviennent conséquemment plus à risque d’être exposé·es à des incidences de cyberintimidation, en tant que cible, témoin ou personne intimidatrice.
        
        L’adolescence est une période cruciale pour le développement identitaire et psychosocial des jeunes. Être la cible d’intimidation durant cette phase critique de développement peut avoir d’importantes conséquences sur le bien-être psychologique et émotionnel et la confiance en soi des jeunes. Ces dernières pourraient également perdurer à l’âge adulte et affecter le fonctionnement psychosocial des personnes sur divers fronts (Lannegrand-Willems, 2012).']);

        Thematique::create(['name'=>'Aîné·es', 'desc' => 'L’intimidation n’a pas d’âge et peut se produire dans des milieux occupés par des personnes de toutes générations, dont les personnes aînées. L’intimidation peut se manifester par des moqueries, de l’exclusion sociale et du commérage entre pairs ou être exercée par tou·te professionnel·le œuvrant auprès de cette population. L’existence de dynamiques de pouvoir entre les professionnel·les et les personnes aînées recevant des soins ou des services peut sérieusement complexifier les situations pour les témoins ou les cibles de l’intimidation.']);

        Thematique::create(['name'=>'École secondaire', 'desc' => 'L’école secondaire représente le milieu de socialisation principal des adolescent·es. Il peut arriver que des dynamiques impliquant des débalancements de pouvoir se produisent avant le secondaire et que ces dernières persistent et même s’accentuent à l’arrivée dans le nouveau milieu scolaire. De nouvelles dynamiques d’intimidation peuvent également se développer en ce milieu. Les personnes qui intimident au secondaire n’ont pas un profil type. Un·e jeune qui intimide peut avoir des comportements perturbateurs à l’école et se comporter adéquatement à la maison (Clinique Psychologie Québec, 2018). Chez les garçons, la forme d’intimidation la plus prévalente est l’intimidation directe (violence physique) et se produirait massivement vers le 3e secondaire (Clinique de Psychologie Québec, 2018). Chez les filles, il s’agit de l’intimidation indirecte (violence relationnelle) et de la cyberintimidation qui se produiraient davantage entre le primaire et le secondaire, puis à nouveau autour du 2e et 3e secondaire (Clinique Psychologie Québec, 2018; Croix-Rouge canadienne, 2023). Au Canada, au moins un·e adolescent·e sur trois aurait été la cible d’intimidation à l’école (Lavigne, R.-M., 2020). Les élèves vivant de l’intimidation peuvent développer de lourdes conséquences psychologiques, telles que la dépression, de l’anxiété, des troubles de concentration et des difficultés scolaires allant d’une
        baisse des notes au décrochage scolaire (Lavigne, R.-M., 2020). Bien que les incidents d’intimidation se produisent majoritairement entre jeunes fréquentant l’école secondaire, il arrive que des parents adoptent des comportements et des attitudes violentes, discriminatoires envers les membres de l’équipe-école, que leur enfant soit impliqué·e dans une incidence d’intimidation ou non. Il importe de rappeler qu’il est attendu de tou·te indivudu·e fréquentant un milieu de respecter le code de vie en place et d’incarner une posture de tolérance zéro envers l’intimidation (Pepler et Craig, 2014).']);

        Thematique::create(['name'=>'Milieux de vie aîné·es', 'desc' => 'Bien que l’intimidation puisse se produire dans tous les lieux fréquentés par les personnes aînées, les milieux de vie collectifs sont ceux où le plus d’incidents d’intimidation sont documentées (INSPQ, 2023a). Les résidences pour aîné·es, qu’elles soient privées ou publiques, ainsi que les CHSLD, sont des établissements d’hébergement offrant aux résident·es des
        espaces communs, tels des salles communautaires, accessibles à tou·tes. Il importe de différencier un incident d’intimidation d’un incident de maltraitance. La maltraitance fait référence aux abus ou négligences commis auprès d’une personne aînée étant dans une relation de confiance et de dépendance avec la ou les personnes initiatrices de la violence, par exemple entre une personne aînée et un·e proche aidant·e ou un·e professionnel·le de la santé (FADOQ, s.d.). Bien que l’intimidation se manifeste généralement entre résident·es dans les milieux de vie aînés, que ce soit verbalement, physiquement, socialement ou matériellement, le
        personnel soignant ou les membres du personnel peuvent être impliqués dans l’événement ou la persistance d’actes ou de dynamiques d’intimidation au sein des établissements (INSPQ, 2023a). Rappelons qu’il est question d’intimidation seulement si la personne aînée n’est pas en situation de dépendance ni dans une relation de confiance avec l’auteur·e de l’intimidation.

        Les conséquences psychologiques et physiques découlant d’actes d’intimidation peuvent être exacerbées lorsque vécues en milieu de vie, puisque les aîné·es ciblé·es peuvent développer une hypervigilance lors de leurs déplacements au sein de leur établissement et ne plus s’y sentir en sécurité. Le caractère hermétique du milieu de vie, le manque de soutien et de prise d’action du personnel face aux dénonciations et un potentiel manque d’options de relocalisation peuvent être des facteurs aggravants chez les aîné·es vivant de l’intimidation dans leur milieu de vie. Ce faisant, il est recommandé que les interventions visant les milieux de vie aînés prennent action auprès de trois instances : les personnes auteures de la violence, les personnes ciblées et l’organisation (INSPQ, 2023a).']);

        Thematique::create(['name'=>'Milieux de loisirs aîné·es', 'desc' => 'À la différence des milieux de vie ainés, les milieux de loisirs tels que les centres communautaires proposant des activités sportives, sociales et culturelles sont des espaces où les personnes aînées peuvent se rassembler de façon sporadique et temporaire, à des fins de socialisation et divertissement. Une personne étant cible d’intimidation en ces lieux peut choisir d’abandonner certaines activités ou de complètement cesser de les fréquenter. La socialisation et le sentiment d’appartenance sont importants à tout âge. Les opportunités sociales peuvent se présenter plus rarement chez les aîné·es, ainsi l’abandon d’une activité ou d’un lieu procurant du bien-être peut avoir des répercussions considérables, notamment sur le plan de l’isolement social, de la santé psychologique et physique (INSPQ, 2023a). L’élaboration de codes de vie bienveillants dans les milieux de loisirs, la formation des membres du personnel quant à la détection de situations d’intimidation et la sensibilisation des participant·es quant aux conséquences de l’intimidation peuvent être des pistes d’intervention entreprises pour viser la réduction des incidences en ces milieux (Gouvernement du Québec, 2016).']);

        Thematique::create(['name'=>'Milieux de loisirs jeunesse', 'desc' => 'Les milieux de loisirs jeunesse sont des espaces où les jeunes peuvent prendre part à des activités tout en rencontrant des personnes de leur âge. Ces espaces participent activement au développement de l’estime de soi, de la confiance en soi et du sentiment d’appartenance des jeunes, des facteurs de protection agissant contre l’intimidation, tout en favorisant leur implication citoyenne et communautaire. Certains milieux de loisirs accueillent les jeunes sur une base volontaire, notamment les maisons des jeunes et les centres de loisirs, tandis que la présence des jeunes dans d’autres lieux, tels les camps de jour et les camps de vacances, peut provenir d’une décision parentale. Un·e enfant vivant de l’intimidation à la maison des jeunes peut cesser de participer aux activités du lieu afin d’éviter des incidences supplémentaires. Un·e enfant vivant de l’intimidation au camp de jour ou au camp de vacances peut toutefois avoir plus de difficultés à éviter des situations d’intimidation subséquentes comme les changements de groupes ou de milieux de camp peuvent être moins accessibles. Les conséquences de l’intimidation vécue pourront ainsi dépendre du type de milieu fréquenté. De plus, les milieux de loisirs peuvent être fréquentés par des enfants et des jeunes se connaissant déjà par le biais de l’école ou de leur quartier. De ce fait, le spectre d’exposition ou de victimisation d’un·e jeune qui subit de l’intimidation dans un tiers lieu, par exemple, à l’école, peut s’élargir en joignant un nouveau milieu fréquenté par les mêmes personnes qui intimident. Les milieux de loisirs jeunesse offrent généralement un encadrement moins formel, laissant davantage d’autonomie et de temps libre aux jeunes. Également, comme les milieux de loisirs jeunesse peuvent être encadrés et supervisés par des adolescent·es et jeunes adultes ayant une expérience minimale, certaines incidences d’intimidation peuvent passer inaperçues ou ne pas faire l’objet d’interventions adéquates pour assurer la protection et le bien-être des jeunes.']);

        Thematique::create(['name'=>'Équipes sportives', 'desc' => 'À la différence des milieux de vie ainés, les milieux de loisirs tels que les centres communautaires proposant des activités sportives, sociales et culturelles sont des espaces où les personnes aînées peuvent se rassembler de façon sporadique et temporaire, à des fins de socialisation et divertissement. Une personne étant cible d’intimidation en ces lieux peut choisir d’abandonner certaines activités ou de complètement cesser de les fréquenter. La socialisation et le sentiment d’appartenance sont importants à tout âge. Les opportunités sociales peuvent se présenter plus rarement chez les aîné·es, ainsi l’abandon d’une activité ou d’un lieu procurant du bien-être peut avoir des répercussions considérables, notamment sur le plan de l’isolement social, de la santé psychologique et physique (INSPQ, 2023a). L’élaboration de codes de vie bienveillants dans les milieux de loisirs, la formation des membres du personnel quant à la détection de situations d’intimidation et la sensibilisation des participant·es quant aux conséquences de l’intimidation peuvent être des pistes d’intervention entreprises pour viser la réduction des incidences en ces milieux (Gouvernement du Québec, 2016).']);

        Thematique::create(['name'=>'Milieux scolaires', 'desc' => 'Les milieux scolaires sont des environnements dans lesquels les enfants et les adolescent·es sont amené·es à développer leurs savoirs et leurs habiletés sociales en relation avec les membres du corps professoral et leurs pairs. Le milieu scolaire constitue le deuxième lieu de socialisation en importance pour les jeunes, après le milieu familial. Les jeunes y apprennent à tisser des liens avec autrui, à gérer des frustrations relationnelles et à développer une maturité émotionnelle leur permettant de contrôler leur agressivité lors de conflits interpersonnels (Boucher, 2009). Dans les milieux scolaires, les moments de transition et les temps morts sont propices aux incidents d’intimidation, soit lors des récréations, sur l’heure du dîner, lors des changements de locaux, à la sortie des classes, etc. Ces moments sont typiquement marqués par une moindre surveillance par les équipes-écoles et une diminution de l’encadrement des élèves (Beaulieu et coll., 2015; Bédard, 2008). Les incidences d’intimidation en milieux scolaires peuvent se produire entre élèves, entre adultes et entre élèves et adultes (Gouvernement du Québec, 2023). Il arrive que des parents d’enfants impliqués dans des incidents d’intimidation ne se montrent pas collaboratifs avec l’équipe-école et contreviennent au code de vie en matière d’intimidation dans leurs propres communications et attitudes envers cette dernière. Il importe de rappeler qu’il est attendu de tou·te indivudu·e fréquentant un milieu de respecter le code de vie en place et d’incarner une posture de tolérance zéro envers l’intimidation (Pepler et Craig, 2014).']);
    }
}
