<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Thematique;

class ThematiquesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Thematique::truncate();

        Thematique::create(['name'=>'Intersectionnalité', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Le cyberespace', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Microagression', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Grossophobie', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Capacitisme', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Sexisme', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Racisme', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Homophobie', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Transphobie', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Classisme', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Âgisme', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Adultisme', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Enfants', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Adolescent·es', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Aîné·es', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'École primaire', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'École secondaire', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Milieux de vie aîné·es', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Milieux de loisirs aîné·es', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Milieux de loisirs jeunesse', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
        Thematique::create(['name'=>'Équipes sportives', 'desc' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet purus fermentum, mollis arcu a, molestie lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean nunc nibh, vehicula nec sagittis eu, aliquam quis diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin tempor, nulla sit amet volutpat faucibus, mi dolor convallis diam, hendrerit laoreet mauris nunc in quam. Sed aliquet sagittis sapien, id condimentum magna lacinia ac. Donec volutpat nisi nec leo pretium imperdiet.']);
    }
}
